DELIMITER //
DROP TRIGGER IF EXISTS create_unverified_prescriptions//
CREATE OR REPLACE TRIGGER create_unverified_prescriptions AFTER INSERT ON tbl_prescriptions FOR EACH ROW BEGIN IF NEW.item_id IS NOT NULL AND NEW.dispensing_status IS NULL THEN insert into patients_with_unverified_prescriptions select NEW.id, NEW.patient_id,NEW.visit_id,t1.medical_record_number,t1.first_name,t1.last_name,t1.middle_name,concat(t1.medical_record_number,t1.first_name,t1.last_name,t1.middle_name),t2.facility_id from tbl_patients t1 join tbl_accounts_numbers t2 on t2.id = NEW.visit_id WHERE t1.id = NEW.patient_id; ELSEIF NEW.dispensing_status = 2 AND EXISTS(SELECT t1.id from tbl_encounter_invoices t1 join tbl_invoice_lines t2 on t1.account_number_id = NEW.visit_id AND t2.patient_id = NEW.patient_id AND t1.id = t2.invoice_id join tbl_item_prices t3 on t2.item_price_id = t3.id AND t3.item_id = NEW.item_id AND (t2.is_payable IS NULL OR t2.status_id = 2)) THEN insert into patients_with_pending_prescriptions select NEW.id, NEW.patient_id,NEW.visit_id,t1.medical_record_number,t1.first_name,t1.last_name,t1.middle_name,concat(t1.medical_record_number,t1.first_name,t1.last_name,t1.middle_name),t2.facility_id from tbl_patients t1 join tbl_accounts_numbers t2 on t2.id = NEW.visit_id WHERE t1.id = NEW.patient_id; END IF; END//
DROP TRIGGER IF EXISTS remove_prescribed_prescriptions//
CREATE OR REPLACE TRIGGER remove_prescribed_prescriptions AFTER UPDATE ON tbl_prescriptions FOR EACH ROW BEGIN IF NEW.dispensing_status = 1 THEN DELETE FROM patients_with_pending_prescriptions WHERE id = NEW.id; END IF; IF NEW.dispensing_status IN (2,3,4) THEN BEGIN DELETE FROM patients_with_unverified_prescriptions WHERE id = NEW.id; END; END IF; DELETE FROM patients_with_unverified_prescriptions WHERE ID = (select id from tbl_prescriptions where tbl_prescriptions.id = patients_with_unverified_prescriptions.id and TIMESTAMPDIFF(day,created_at,current_date) > (select days from tbl_reattendance_free_days where facility_id = patients_with_unverified_prescriptions.facility_id)); DELETE FROM patients_with_pending_prescriptions WHERE ID = (select id from tbl_prescriptions where tbl_prescriptions.id = patients_with_pending_prescriptions.id and TIMESTAMPDIFF(day,created_at,current_date) > (select days from tbl_reattendance_free_days where facility_id = patients_with_pending_prescriptions.facility_id)); END//
DELIMITER ;
truncate patients_with_unverified_prescriptions;
truncate patients_with_pending_prescriptions;
insert into patients_with_unverified_prescriptions select t1.id, t1.patient_id,t1.visit_id,t2.medical_record_number,t2.first_name,t2.last_name,t2.middle_name, concat(t2.medical_record_number,t2.first_name,t2.last_name,t2.middle_name),t3.facility_id from  tbl_prescriptions t1 inner join tbl_patients t2 on t1.item_id is not null and t1.dispensing_status IS NULL and t1.patient_id = t2.id join tbl_accounts_numbers t3 on t3.id = t1.visit_id join tbl_reattendance_free_days t4 on t4.facility_id = t3.facility_id and timestampdiff(day, t1.created_At, current_date) <= t4.days group by t1.id;
insert into patients_with_pending_prescriptions select t1.id, t1.patient_id,t1.visit_id,t2.medical_record_number,t2.first_name,t2.last_name,t2.middle_name, concat(t2.medical_record_number,t2.first_name,t2.last_name,t2.middle_name),t3.facility_id from tbl_item_prices t0 inner join tbl_prescriptions t1 on t1.dispensing_status = 2 and t0.item_id = t1.item_id join tbl_invoice_lines t3 on t3.item_price_id = t0.id and t3.patient_id = t1.patient_id and (t3.status_id = 2 or t3.payment_filter = 3 or t3.is_payable is not true) inner join tbl_patients t2 on t1.patient_id = t2.id inner join tbl_encounter_invoices t4 on t4.id = t3.invoice_id and t1.visit_id = t4.account_number_id join tbl_reattendance_free_days t5 on t5.facility_id = t4.facility_id and timestampdiff(day, t1.created_At, current_date) <= t5.days group by t1.id;